version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/boilerplate?authSource=admin
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: