version: '3.8'

services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    hostname: mongo
    restart: unless-stopped
    command: ["mongod", "--replSet=RS"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-init:
    image: mongo:6.0.5
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: [ "sh", "-c", "mongosh --host mongo --quiet --eval 'rs.initiate()'" ]
